//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 11:14:09 AM EET 
//


package eu.europa.esig.dss.diagnostic.jaxb;

import jakarta.xml.bind.annotation.adapters.XmlAdapter;
import eu.europa.esig.dss.enumerations.MaskGenerationFunction;

public class Adapter27
    extends XmlAdapter<String, MaskGenerationFunction>
{


    public MaskGenerationFunction unmarshal(String value) {
        return (eu.europa.esig.dss.jaxb.parsers.MaskGenerationFunctionParser.parse(value));
    }

    public String marshal(MaskGenerationFunction value) {
        return (eu.europa.esig.dss.jaxb.parsers.MaskGenerationFunctionParser.print(value));
    }

}
