//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 11:14:09 AM EET 
//


package eu.europa.esig.dss.diagnostic.jaxb;

import jakarta.xml.bind.annotation.adapters.XmlAdapter;
import eu.europa.esig.dss.enumerations.CertificateStatus;

public class Adapter17
    extends XmlAdapter<String, CertificateStatus>
{


    public CertificateStatus unmarshal(String value) {
        return (eu.europa.esig.dss.jaxb.parsers.CertificateStatusParser.parse(value));
    }

    public String marshal(CertificateStatus value) {
        return (eu.europa.esig.dss.jaxb.parsers.CertificateStatusParser.print(value));
    }

}
