//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.09 at 12:15:26 AM EEST 
//


package eu.europa.esig.dss.diagnostic.jaxb;

import jakarta.xml.bind.annotation.adapters.XmlAdapter;
import eu.europa.esig.dss.enumerations.ArchiveTimestampType;

public class Adapter16
    extends XmlAdapter<String, ArchiveTimestampType>
{


    public ArchiveTimestampType unmarshal(String value) {
        return (eu.europa.esig.dss.jaxb.parsers.ArchiveTimestampTypeParser.parse(value));
    }

    public String marshal(ArchiveTimestampType value) {
        return (eu.europa.esig.dss.jaxb.parsers.ArchiveTimestampTypeParser.print(value));
    }

}
