//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.17 at 11:14:15 AM EET 
//


package eu.europa.esig.dss.simplecertificatereport.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementWrapper;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SimpleCertificateReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleCertificateReport"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ValidationPolicy" type="{http://dss.esig.europa.eu/validation/simple-certificate-report}ValidationPolicy"/&gt;
 *         &lt;element name="Chain" type="{http://dss.esig.europa.eu/validation/simple-certificate-report}Chain" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ValidationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleCertificateReport", propOrder = {
    "validationPolicy",
    "chain"
})
public class XmlSimpleCertificateReport implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ValidationPolicy", required = true)
    protected XmlValidationPolicy validationPolicy;
    @XmlElementWrapper(name = "Chain")
    @XmlElement(name = "ChainItem", namespace = "http://dss.esig.europa.eu/validation/simple-certificate-report")
    protected List<XmlChainItem> chain = new ArrayList<XmlChainItem>();
    @XmlAttribute(name = "ValidationTime")
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Date validationTime;

    /**
     * Gets the value of the validationPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link XmlValidationPolicy }
     *     
     */
    public XmlValidationPolicy getValidationPolicy() {
        return validationPolicy;
    }

    /**
     * Sets the value of the validationPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlValidationPolicy }
     *     
     */
    public void setValidationPolicy(XmlValidationPolicy value) {
        this.validationPolicy = value;
    }

    /**
     * Gets the value of the validationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getValidationTime() {
        return validationTime;
    }

    /**
     * Sets the value of the validationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationTime(Date value) {
        this.validationTime = value;
    }

    public List<XmlChainItem> getChain() {
        return chain;
    }

    public void setChain(List<XmlChainItem> chain) {
        this.chain = chain;
    }

}
