name: "Android CI"
on: push
jobs:
  instrumentation-tests:
    name: Instrumentation Tests
    runs-on: self-hosted
    timeout-minutes: 6000
    strategy:
      # Allow tests to continue on other devices if they fail on one device.
      fail-fast: false
      matrix:
#         device:
#            - "emulator-5554"
        cores: 
          - 4
        api-level: [26,32]
        heap-size:
          - 128M

    steps:
      - name: Fetch Source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        env:
            GPR_USER: ${{ secrets.GITHUB_ACTOR }}
            GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          script: adb logcat *:S TestRunner:V & ./gradlew connectedCheck --no-build-cache --no-daemon --stacktrace

  instrumentation-test-summary:
    if: ${{ always() }}
    runs-on: self-hosted
    name: Instrumentation Test Matrix Summary
    needs: instrumentation-tests

    steps:
      - name: Check build matrix status
        if: ${{ needs.instrumentation-tests.result != 'success' }}
        run: exit 1

  publish-snapshot:
    name: Publish github packages
    runs-on: self-hosted
    if: "github.event_name == 'push'"
    needs:
      - instrumentation-test-summary

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Upload Snapshot
        run: ./gradlew publish
        env:
          GPR_USER: ${{ secrets.GITHUB_ACTOR }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
